# docker-compose.yml
version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    ports:
      - "80:80"
    depends_on:
      - server
  
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/ai-market-analyst
      - JWT_SECRET=your_jwt_secret
      - CLIENT_URL=http://localhost
    depends_on:
      - mongo
  
  mongo:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: